#!/usr/bin/python3
import sys
file_name: str = sys.argv[1]

with open(file_name) as f:
    lines = f.readlines()
    for line in lines:
        num = int(line)
        median = int(num / 2) + 1
        start = 2 if (num % 2 == 0) else 3

        for div in range(start, median, 2):
            if (num % div == 0):
                print(f"{num}={int(num/div)}*{div}")
                break
